### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by gregorysprenger** [bacterial-genomics/wf-paired-end-illumina-assembly#12]
### Description of the bug

**Current behavior:**
The `wf-paired-end-illumina-assembly pipeline documentation` link in the `Bug report` issue template is broken.

**Expected behavior:**
Check all links in repo to make sure they work.

### Command used and terminal output

N/A

### Relevant files

.github/ISSUE_TEMPLATE/bug_report.yml

### System information

N/A

**Comment by chrisgulvik** [comment]
- setup `markdown-link-check` https://github.com/marketplace/actions/markdown-link-check or perhaps https://github.com/UmbrellaDocs/linkspector (not yet in marketplace) to verify all links in README.md files are alive not dead
