### ISSUE TITLE
GitLeaks in MegaLinter is not ignoring FastA files

### ISSUE THREAD

**Issue by gregorysprenger** [bacterial-genomics/wf-paired-end-illumina-assembly#64]
### Description of the bug

GitLeaks in MegaLinter is not ignoring FastA files in the `bin/` directory. It thinks that each line is a possible aws token.

Documentation is pretty sparse on how to ignore an entire file. May possibly have to create a `.gitleaks~` ignore file to ignore each line that it detects in FastA files.

### Relevant files

.mega-linter.yml

**Comment by chrisgulvik** [comment]
fixed with https://github.com/bacterial-genomics/wf-paired-end-illumina-assembly/pull/67
